---
- name: Manage Rolebindings For Principal, Role and Cluster Scope
  uri:
    url: "{{mds_server_url}}/security/1.0/principals/{{item.principal}}/roles/{{ item.role }}"
    method: "{{http_method}}"
    validate_certs: false
    force_basic_auth: true
    url_username: "{{mds_user}}"
    url_password: "{{mds_user_password}}"
    body_format: json
    body: "{ \"clusterName\": \"{{item.clusterName}}\" }"
    status_code: 204
  loop: "{{ rbac_list }}"
  when: item.role | regex_search("^\w+Admin$") != none

- name: Manage Rolebindings For Principal, Scope and Set of resources
  uri:
    url: "{{mds_server_url}}/security/1.0/principals/{{item.principal}}/roles/{{ item.role }}/bindings"
    method: "{{http_method}}"
    validate_certs: false
    force_basic_auth: true
    url_username: "{{mds_user}}"
    url_password: "{{mds_user_password}}"
    body_format: json
    status_code: 204
    body: "{ \"scope\": { \"clusterName\": \"{{item.clusterName}}\" }, \"resourcePatterns\": {{item.resources}} }"
  loop: "{{ rbac_list }}"
  when: item.role | regex_search("^\w+Admin$") == none
