---
# get RBAC roles
- name: Get Roles List
# read roles and cache them
  uri:
    url: "{{mds_server_url}}/security/1.0/roleNames"
    method: GET
    validate_certs: false
    force_basic_auth: true
    force: yes
    url_username: "{{mds_user}}"
    url_password: "{{mds_user_password}}"
    body_format: json
  register: roles_list
  check_mode: no

- debug:
    msg="{{roles_list.json}}"
    verbosity=3

- name: Cache Roles List
  set_fact:
    roles_cached: "{{roles_list.json}}"
