---
- name: Quotas management
  gather_facts: false
  hosts: localhost
  environment: "{{proxy_env}}"

  tasks:
  - name: Set Variables
    import_role:
      name: common
      
  - name: Process Quota
    import_role: 
      name: quota
