---
- name: Topics management
  gather_facts: false
  hosts: "{{ run_host|default('localhost') }}"
  environment: "{{proxy_env}}"

  tasks:
  - name: Set Variables
    import_role:
      name: common
      
  - name: Process Topics
    import_role: 
      name: topic
