---
# Low level topic operations - using Confluent Server v3 API
# delete reports success for topics that do not exist
- name: Delete Topics
  uri:
    url: "{{res_server_url}}{{topic_cluster_prefix}}/v3/clusters/{{cluster_id}}/topics/{{item}}"
    method: DELETE
    validate_certs: false
    force_basic_auth: true
    url_username: "{{rest_user}}"
    url_password: "{{rest_user_password}}"
  register: result
  failed_when: result.status != 204 and result.json.error_code|int != 40403
  loop: "{{ topics_in }}"
 
