---
# Low level topic operations - using Confluent Server v3 API
- name: Add partitions
# not supported via REST API yet - needs direct call to Kafka Admin API
  shell: |
    {{ binary_base_path }}/bin/kafka-topics --bootstrap-server {{kafka_broker_hostname}}:{{kafka_broker_port}} \
      --alter --topic {{ item.topic_name }} --partitions {{ item.partitions_count }} --command-config {{kafka_broker_client_config_file}}
  environment:
    CONFLUENT_SECURITY_MASTER_KEY: "{{ secrets_protection_masterkey }}"
  register: topics_result
  # stdout_lines will have topics with URPs and stderr has WARN and ERROR level logs
  until: topics_result.stdout_lines|length == 0 and 'ERROR' not in topics_result.stderr
  changed_when: "topics_result.rc == 0"
  loop: "{{topics_in}}"

