---
- name: Write to a file  
  block:
    - name: Dump To A File
      local_action: copy content='{{to_dump | to_nice_yaml(indent=2)}}' dest="{{topic_dump_destination}}"
      check_mode: no
      vars:
        to_dump: "{{ {'topics': topics_current} }}"    
      no_log: False
  when: 
    - topic_dump_file

