---
# Low level topic operations - using Confluent Server v3 API
- name: Update topics
  uri:
    url: "{{rest_server_url}}{{topic_cluster_prefix}}/v3/clusters/{{cluster_id}}/topics/{{item.topic_name}}/configs:alter"
    method: POST
    validate_certs: false
    force_basic_auth: true
    url_username: "{{rest_user}}"
    url_password: "{{rest_user_password}}"
    headers:
      Content-Type: application/json
    body_format: json
    body: >
      {
        "data" :{{item.configs| to_json | from_json}}
      }
    status_code: 204
  loop: "{{ topics_in |flatten(levels=1) }}"

