---
# make out delta operation from the existing and intended quotas setup
# input quotas_current - current state; quotas - desired state
- debug:
    msg="Current state>{{ quotas_current }}"
    verbosity=3
- debug:
    msg="Desired state>{{ quotas }}"   
    verbosity=3

- name: Initialize Variables         
  set_fact:
    quotas_to_add: []
    quotas_to_delete: []

- name: To add
# check the quotas to add, figure out the key additions and value updates 
  # debug:
  #   msg:
  #   - "{{item}}"
  #   - "{{diff_keys}}"
  set_fact:
    quotas_to_add: "{{ quotas_to_add+[item.0]}}"
  loop: "{{ (quotas_to_reconfigure_raw + quotas_current) | groupby('client_id')}}"    
  vars:
     skeys: "{{ item.1.0.keys()|d([])|list }}"
     tem: "{{ item.1.1 | d({})}}"
     tkeys: "{{ tem.keys()| d([])|list }}"
     diff_keys: "{{ skeys|difference(tkeys) }}"
     svals: "{{ item.1.0.values()|d([])|list }}"
     temv: "{{ item.1.1 | d({})}}"
     tvals: "{{ tem.values()| d([])|list }}"
     diff_vals: "{{ svals|difference(tvals) }}"
     quotas_to_reconfigure_raw: "{{quotas | difference(quotas_current) }}"
     to_add_list: "{{quotas | map(attribute='client_id') | difference(quotas_current | map(attribute='client_id')) | list}}"
  when: item.0 in to_add_list or tem and (diff_keys|length != 0 or diff_vals|length !=0)     


- name: To delete quotas
    # check the quotas for removals, the rest can be processed as is 
  set_fact:
    quotas_to_delete: "{{ quotas_to_delete|d([])+[{'client_id': item.0, 'delete': diff_keys|difference(['client_id'])}]}}"
  # debug:
  #   msg:
  #   - "{{item}}"
  #   - "{{diff_keys}}"
  loop: "{{ (quotas_to_reconfigure_raw + quotas_current) | groupby('client_id')}}"    
  vars:
     skeys: "{{ item.1.0.keys()|d([])|list }}"
     tem: "{{ item.1.1 | d({})}}"
     tkeys: "{{ tem.keys()| d([])|list }}"
     diff_keys: "{{ skeys|difference(tkeys) if item.0 in to_delete_list else tkeys|difference(skeys) }}"
     quotas_to_reconfigure_raw: "{{quotas | difference(quotas_current) }}"
     to_delete_list: "{{quotas_current | map(attribute='client_id') | difference(quotas | map(attribute='client_id')) | list}}"
  when: item.1.0.client_id not in quotas_to_add and diff_keys|length != 0     

- debug:
    var: quotas_to_add
    verbosity: 2
- debug:
    var: quotas_to_delete
    verbosity: 2
