---
# connectivity variables
sr_port: 8081  
proxy_env: {}
ansible_fqdn: ""
topic_protected: ^_confluent.*|^_connect.*|^_ksql.*|^_schemas|^confluent.*
topics_key_t0: []
topics_value_t0: []
topics_key: []
topics_value: []
key_flat: []
key_flat_add: []
value_flat: []
value_flat_add: []
Combined_flat: []
sub_list: []
schemas_current: []
record_schemas: []  
key_file_path: ""
crt_file_path: ""
rootcrt_file_path: ""
delete_all_schemas: false  

schemas:
  records_schemas:
    - record_name: "samplerecordonly"
      compatibility: "BACKWARD"
      schema_file_src_path: "samplerecordonlyavro.avsc"
  topics:
    - name: test
      key:
        schema_file_src_path: "/home/<user>/testkey.avsc"
      value:
        schema_file_src_path: "/home/<user>/testvalue.avsc"
      
